import { test } from 'node:test';
import assert from 'node:assert/strict';
import { subir } from './ajuda.js';
import { exec, um, todos } from '../src/db.js';
import { salvarConfig } from '../src/config.js';
import { MODELOS_PAINEL } from '../src/paineis-modelos.js';
import { extrairSugestao, validarLinhas } from '../src/paineis.js';
const LINHA={fornecedor:'Fornecedor Exemplo',documento:'Certidão',situacao:'pendente',pendencia:'Documento vencido'};
const TEXTO='Fornecedor Exemplo | Certidão | pendente | Documento vencido';
function seed(app,q,p,{teste=0,sigilosa=0,status='parcial',texto=TEXTO}={}) {
 const em=app.agora().toISOString();
 const c=Number(exec(app.db,'insert into conversas(pessoa_id,quick_win_id,teste,sigilosa,criado_em,atualizado_em) values(?,?,?,?,?,?)',p,q,teste,sigilosa,em,em).lastInsertRowid);
 const m=Number(exec(app.db,"insert into mensagens(conversa_id,papel,texto,criado_em) values(?,'assistant',?,?)",c,texto,em).lastInsertRowid);
 exec(app.db,"insert into roteamento(em,pessoa_id,conversa_id,resposta_id,quick_win_id,modo,complexidade,resultado,versao,qualidade) values(?,?,?,?,?,'auto','baixa','respondido','teste',?)",em,p,c,m,q,JSON.stringify({status}));return {c,m};
}
async function setup(t,{modelo='fornecedores',ia}={}) {
 const S=await subir(ia?{ia}:{});t.after(()=>S.fechar());const a=await S.cliente().entrar('admin@exemplo.com.br');
 salvarConfig(S.app.db,{dominios:['exemplo.com.br']});
 await a.post('/api/admin/pessoas',{email:'usuario@exemplo.com.br',nome:'Usuário'});
 const u=await S.cliente().entrar('usuario@exemplo.com.br');
 const q=(await a.post('/api/quick-wins',{nome:'Processo QA',toda_empresa:true,painel_modelo:modelo})).dados;
 exec(S.app.db,"update quick_wins set status='em_uso' where id=?",q.id);
 const f=seed(S.app,q.id,a.pessoa.id);
 const b=`/api/quick-wins/${q.id}/painel`;
 return {S,a,u,q,f,b,async preparar(){const r=await a.post(`${b}/preparar`,{mensagem:f.m});assert.equal(r.status,200,JSON.stringify(r.dados));return r.dados;},async confirmar(d,extra={}) {return a.post(`${b}/registros/${d.id}`,{dados:[LINHA],versao:d.versao,escopo:'pessoal',confirmado:true,cienteParcial:true,...extra});}};
}
test('catálogo, preparação atômica e nenhuma publicação automática',async t=>{const s=await setup(t);assert.equal((await s.a.get('/api/paineis-modelos')).dados.modelos.length,2);assert.equal(s.q.painel.modelo,'fornecedores');assert.equal(um(s.S.app.db,'select versao_publicada from quick_wins where id=?',s.q.id).versao_publicada,null);assert.equal((await s.a.post('/api/quick-wins',{nome:'Inválido',painel_modelo:'livre',toda_empresa:true})).status,400);assert.equal((await s.u.post(s.b,{modelo:'acoes'})).status,403);assert.equal((await s.a.post(s.b,{modelo:'acoes'})).status,409);});
test('dados preparados não contam; confirmação e repetição não duplicam registros',async t=>{const s=await setup(t),d=await s.preparar();assert.equal(d.estado,'rascunho');assert.equal((await s.a.get(s.b)).dados.total,0);assert.equal((await s.confirmar(d)).status,200);assert.equal((await s.a.get(s.b)).dados.total,1);const reprise=await s.preparar();assert.equal(reprise.id,d.id);assert.equal(reprise.estado,'confirmado');assert.equal((await s.confirmar(d)).status,400);assert.equal(um(s.S.app.db,'select count(*) n from qw_painel_registros').n,1);});
test('registro privado invisível até confirmação explícita de compartilhamento; conversa permanece privada',async t=>{const s=await setup(t),d=await s.preparar();await s.confirmar(d);assert.equal((await s.u.get(s.b)).dados.total,0);const atual=await s.preparar();assert.equal((await s.confirmar(atual,{escopo:'equipe',motivo:'Compartilhar campos conferidos'})).status,200);const vista=(await s.u.get(s.b)).dados;assert.equal(vista.total,1);assert.equal(vista.registros[0].conversa,null);assert.equal(vista.registros[0].mensagem,null);assert.equal((await s.u.get(`${s.b}/registros/${d.id}`)).status,404);assert.equal((await s.u.get(`/api/conversas/${s.f.c}`)).status,404);assert.equal((await s.u.post(`${s.b}/preparar`,{mensagem:s.f.m})).status,404);});
test('nova proteção de sigilo esconde dados anteriormente compartilhados',async t=>{const s=await setup(t),d=await s.preparar();await s.confirmar(d,{escopo:'equipe'});exec(s.S.app.db,'update conversas set sigilosa=1 where id=?',s.f.c);assert.equal((await s.u.get(s.b)).dados.total,0);assert.equal((await s.a.get(s.b)).dados.total,1);assert.equal((await s.confirmar(await s.preparar(),{escopo:'equipe',motivo:'Correção'})).status,403);});
test('resultado de teste é visível para revisão, mas não entra no histórico',async t=>{const s=await setup(t);exec(s.S.app.db,'update conversas set teste=1 where id=?',s.f.c);const d=await s.preparar();assert.equal(d.teste,true);assert.equal((await s.confirmar(d)).status,409);assert.equal((await s.a.get(s.b)).dados.total,0);});
test('pergunta, inconsistência, falta de conferência e conteúdo não guardado não geram registros',async t=>{const s=await setup(t);for(const status of ['pergunta','inconsistente','desconhecido']){const f=seed(s.S.app,s.q.id,s.a.pessoa.id,{status});assert.equal((await s.a.post(`${s.b}/preparar`,{mensagem:f.m})).status,409);}const f=seed(s.S.app,s.q.id,s.a.pessoa.id,{texto:'[Conteúdo processado e não guardado, pela política de retenção da empresa.]'});assert.equal((await s.a.post(`${s.b}/preparar`,{mensagem:f.m})).status,409);});
test('parcial exige ciência; validação bloqueia campo ausente, estado inválido e confirmação ausente',async t=>{const s=await setup(t),d=await s.preparar();for(const extra of [{confirmado:false},{cienteParcial:false},{dados:[{...LINHA,fornecedor:''}]},{dados:[{...LINHA,situacao:'aprovado'}]}])assert.equal((await s.confirmar(d,extra)).status,400);assert.equal((await s.a.get(s.b)).dados.total,0);});
test('correção mantém mês de confirmação, exige motivo e versão atual; revisões auditáveis',async t=>{const s=await setup(t),d=await s.preparar();await s.confirmar(d);const atual=await s.preparar();assert.equal((await s.confirmar(atual)).status,400);assert.equal((await s.confirmar(atual,{versao:1,motivo:'Correção'})).status,409);const antes=(await s.a.get(s.b)).dados.meses;assert.equal((await s.confirmar(atual,{dados:[{...LINHA,situacao:'conferido',pendencia:''}],motivo:'Documento renovado'})).status,200);const painel=(await s.a.get(s.b)).dados;assert.equal(painel.meses[0].mes,antes[0].mes);assert.equal(painel.situacoes.conferido,1);assert.equal(painel.situacoes.pendente,0);assert.equal(todos(s.S.app.db,'select * from qw_painel_revisoes').length,2);});
test('retirada com motivo recalcula indicadores e impede nova confirmação',async t=>{const s=await setup(t),d=await s.preparar();await s.confirmar(d);const atual=await s.preparar();assert.equal((await s.a.post(`${s.b}/registros/${d.id}/retirar`,{versao:atual.versao})).status,400);assert.equal((await s.a.post(`${s.b}/registros/${d.id}/retirar`,{versao:atual.versao,motivo:'Caso duplicado em outra execução'})).status,200);assert.equal((await s.a.get(s.b)).dados.total,0);assert.equal((await s.confirmar(await s.preparar(),{motivo:'Reabrir'})).status,409);});
test('apagar conversa apaga registros e revisões por retenção, sem dados órfãos',async t=>{const s=await setup(t),d=await s.preparar();await s.confirmar(d);await s.a.del(`/api/conversas/${s.f.c}`);assert.equal((await s.a.get(s.b)).dados.total,0);assert.equal(um(s.S.app.db,'select count(*) n from qw_painel_registros').n,0);assert.equal(um(s.S.app.db,'select count(*) n from qw_painel_revisoes').n,0);});
test('governança de armazenamento e credenciais continua aplicada a dados conferidos manualmente',async t=>{const s=await setup(t),d=await s.preparar();salvarConfig(s.S.app.db,{naoArmazenar:['cpf']});assert.equal((await s.confirmar(d,{dados:[{...LINHA,pendencia:'CPF 529.982.247-25'}]})).status,403);assert.equal((await s.confirmar(d,{dados:[{...LINHA,pendencia:'sk-or-v1-'+'a'.repeat(64)}]})).status,400);});
test('usuário de consulta não grava nem prepara',async t=>{const s=await setup(t),d=await s.preparar();s.S.app.tenant={companyId:'qa'};assert.equal((await s.a.post(`${s.b}/preparar`,{mensagem:s.f.m})).status,403);assert.equal((await s.confirmar(d)).status,403);});
test('estado agregado e data de ações são validados, não inferidos pelo painel',()=>{const m=MODELOS_PAINEL.acoes;assert.throws(()=>validarLinhas(m,[{acao:'Revisar',responsavel:'',prazo:'2026-02-30',situacao:'pendente'}]));assert.deepEqual(validarLinhas(m,[{acao:'Revisar',responsavel:'',prazo:'2026-10-10',situacao:'pendente'}])[0],{acao:'Revisar',responsavel:'',prazo:'2026-10-10',situacao:'pendente'});});
test('extração descarta campos sem evidência literal e não aceita dados ou estados fora do catálogo',()=>{const m=MODELOS_PAINEL.fornecedores;const s=extrairSugestao(m,JSON.stringify({itens:[{fornecedor:{valor:'Inventado',trecho:'não existe'},documento:{valor:'Certidão',trecho:'Certidão'},situacao:{valor:'aprovado',trecho:'pendente'}}]}),TEXTO);assert.equal(s.dados[0].fornecedor,'');assert.equal(s.dados[0].documento,'Certidão');assert.equal(s.dados[0].situacao,'nao_informado');assert.equal(extrairSugestao(m,'texto livre',TEXTO),null);});
test('sugestão governada prepara campos, contabiliza custo e reaproveita sem nova chamada',async t=>{let chamadas=0;const ia={async *enviar(){chamadas++;yield {tipo:'texto',texto:JSON.stringify({itens:[Object.fromEntries(Object.entries(LINHA).map(([k,v])=>[k,{valor:v,trecho:v}]))]})};yield {tipo:'fim',custo:0.001,modelo:'mistralai/mistral-small'};}};const s=await setup(t,{ia});await s.a.put('/api/admin/modelos/mistralai%2Fmistral-small',{liberado:true,perfil:'rapido'});const [d,e]=await Promise.all([s.preparar(),s.preparar()]);assert.deepEqual(d.dados,[LINHA]);assert.equal(d.id,e.id);assert.equal(chamadas,1);await s.preparar();assert.equal(chamadas,1);assert.equal(um(s.S.app.db,"select count(*) n from roteamento where origem='painel_registro'").n,1);assert.ok(um(s.S.app.db,'select sum(custo) custo from uso').custo>0);});
test('paginação conserva todos os indicadores e permite alcançar registros anteriores',async t=>{const s=await setup(t),d=await s.preparar();await s.confirmar(d);const row=um(s.S.app.db,'select * from qw_painel_registros where id=?',d.id);for(let i=0;i<51;i++){const f=seed(s.S.app,s.q.id,s.a.pessoa.id);exec(s.S.app.db,"insert into qw_painel_registros(quick_win_id,conversa_id,mensagem_id,pessoa_id,estado,dados,confirmado_em,criado_em,atualizado_em) values(?,?,?,?,'confirmado',?,?,?,?)",s.q.id,f.c,f.m,s.a.pessoa.id,row.dados,row.confirmado_em,row.criado_em,row.atualizado_em);}const primeira=(await s.a.get(s.b)).dados,segunda=(await s.a.get(`${s.b}?pagina=2`)).dados;assert.equal(primeira.total,52);assert.equal(primeira.registros.length,50);assert.equal(segunda.registros.length,2);assert.equal(segunda.total,52);assert.equal(segunda.pagina,2);assert.equal((await s.u.get(`${s.b}?pagina=2`)).dados.total,0);});
test('sigilo não dispara chamada de extração e compartilhamento segue bloqueado',async t=>{let chamadas=0;const s=await setup(t,{ia:{async *enviar(){chamadas++;}}});exec(s.S.app.db,'update conversas set sigilosa=1 where id=?',s.f.c);const d=await s.preparar();assert.equal(chamadas,0);assert.equal(d.motivo,'sigilo');assert.equal(d.podeCompartilhar,false);assert.equal((await s.confirmar(d,{escopo:'equipe'})).status,403);});
test('falha de IA mantém caminho manual, sem incluir dados no histórico',async t=>{const s=await setup(t,{ia:{async *enviar(){throw new Error('QA indisponível');}}});await s.a.put('/api/admin/modelos/mistralai%2Fmistral-small',{liberado:true,perfil:'rapido'});const d=await s.preparar();assert.equal(d.motivo,'falha_preparacao');assert.equal(d.dados[0].fornecedor,'');assert.equal((await s.a.get(s.b)).dados.total,0);assert.equal((await s.confirmar(d)).status,200);});
test('datas mensais respeitam Brasília, revisões têm motivo e não expõem dados a terceiros',async t=>{const s=await setup(t);s.S.app.agora=()=>new Date('2026-11-01T01:30:00Z');await s.a.entrar('admin@exemplo.com.br');await s.u.entrar('usuario@exemplo.com.br');const d=await s.preparar();await s.confirmar(d);assert.equal((await s.a.get(s.b)).dados.meses[0].mes,'2026-10');const r=(await s.a.get(`${s.b}/registros/${d.id}`)).dados;assert.equal(r.revisoes.length,1);assert.equal(r.revisoes[0].motivo,'Conferência inicial');assert.equal((await s.u.get(`${s.b}/registros/${d.id}`)).status,404);});
