import {test} from 'node:test';
import assert from 'node:assert/strict';
import {abrirBanco,exec,todos,um} from '../src/db.js';
import {lerConfig,salvarConfig} from '../src/config.js';
import {semearSugestao,ampliarPoolsRecomendados,atualizarCatalogo,acharModelo,resolverClasse} from '../src/modelos.js';
import {POOLS_RECOMENDADOS} from '../src/pools-modelos.js';
import {analisarPedido,rotear,AUTOMATICO,desempenhoRecente} from '../src/roteador.js';
const agora=new Date('2026-10-06T02:00:00Z');
const catalogo=POOLS_RECOMENDADOS.map(p=>({id:p.id,nome:p.id,contexto:1000000,precoEntrada:(p.perfil==='rapido'?0.2:p.perfil==='equilibrado'?0.8:2)/1e6,precoSaida:(p.perfil==='rapido'?1:p.perfil==='equilibrado'?4:10)/1e6}));
function app(){const db=abrirBanco(':memory:');semearSugestao(db);return {db,agora:()=>agora,catalogo,ia:{listarModelos:async()=>catalogo}};}
function escolher(a,pedido=AUTOMATICO,extra={}){const cfg=lerConfig(a.db);return rotear({db:a.db,cfg,pessoa:{grupos:[],areas:[]},pedido,analise:analisarPedido({texto:'Reescreva esta frase curta: a reunião terminou.'}),modeloManual:pedido===AUTOMATICO?null:acharModelo(a.db,cfg,resolverClasse(a.db,cfg,pedido)),agora,...extra});}
function observacao(a,id,resultado,ms=1000,em=agora.toISOString(),usado=null){exec(a.db,"insert into roteamento (em,modo,complexidade,modelo,modelo_usado,resultado,ms_primeiro_token) values (?,'automatico','simples',?,?,?,?)",em,id,usado,resultado,ms);}

test('catálogo confirmado amplia para três modelos por nível e registra uma única inclusão idempotente',async()=>{const a=app();try{await atualizarCatalogo(a);assert.equal(todos(a.db,'select * from modelos').length,9);for(const perfil of ['rapido','equilibrado','avancado'])assert.equal(todos(a.db,'select * from modelos where perfil=? and liberado=1',perfil).length,3);assert.equal(todos(a.db,"select * from eventos where tipo='model.pool_expanded'").length,1);assert.deepEqual(ampliarPoolsRecomendados(a),[]);assert.equal(todos(a.db,'select * from modelos where homologado=1').length,0);assert.equal(lerConfig(a.db).padroes.rapido,'google/gemini-3.5-flash-lite');}finally{a.db.close();}});
test('modo manual, modelos desativados, vetos e capacidades existentes nunca são sobrescritos',()=>{const a=app();try{salvarConfig(a.db,{governanca:{modo:'manual'}});assert.deepEqual(ampliarPoolsRecomendados(a),[]);salvarConfig(a.db,{governanca:{modo:'recomendado'}});exec(a.db,"insert into modelos(id,nome,fornecedor,perfil,liberado,vetado_plataforma,capacidades) values ('openai/gpt-5-mini','Manual','openai','avancado',0,1,'{\"geral\":2}')");ampliarPoolsRecomendados(a);const m=um(a.db,"select * from modelos where id='openai/gpt-5-mini'");assert.equal(m.liberado,0);assert.equal(m.perfil,'avancado');assert.equal(m.vetado_plataforma,1);assert.equal(m.capacidades,'{"geral":2}');}finally{a.db.close();}});
test('falta de catálogo, preço inválido, teto excedido e contexto desconhecido não liberam novos recursos',async()=>{const a=app();try{const alvo=catalogo.find(x=>x.id==='openai/gpt-5-mini');for(const patch of [{precoEntrada:NaN},{precoSaida:0},{precoEntrada:1},{contexto:null}])assert.deepEqual(ampliarPoolsRecomendados(a,[{...alvo,...patch}]),[]);assert.deepEqual(ampliarPoolsRecomendados(a,[]),[]);a.ia.listarModelos=async()=>[];await assert.rejects(atualizarCatalogo(a),/preservada/);assert.equal(todos(a.db,'select * from modelos where no_catalogo=1').length,3);}finally{a.db.close();}});
test('escolha de cada nível compara seus modelos em vez de fixar o padrão; Automático usa o menor nível suficiente',()=>{const a=app();try{ampliarPoolsRecomendados(a);salvarConfig(a.db,{acessoPerfis:{equilibrado:{todos:true},avancado:{todos:true}},roteamento:{ativo:true,preferencia:'economia'}});for(const perfil of ['rapido','equilibrado','avancado']){const r=escolher(a,'classe:'+perfil,{origem:'pessoa'});assert.equal(r.modelo.perfil,perfil);assert.equal(r.motivoEscolha,'melhor_modelo_no_nivel');assert.ok(r.reserva);assert.equal(acharModelo(a.db,lerConfig(a.db),r.reserva).perfil,perfil);assert.equal(r.candidatos.filter(c=>c.classe===perfil).length,3);}assert.equal(escolher(a).modelo.perfil,'rapido');}finally{a.db.close();}});
test('capacidade explícita relevante vence opção insuficiente dentro do mesmo nível',()=>{const a=app();try{ampliarPoolsRecomendados(a);salvarConfig(a.db,{acessoPerfis:{equilibrado:{todos:true}},roteamento:{ativo:true,preferencia:'economia'}});exec(a.db,"update modelos set capacidades=? where id='openai/gpt-5.4-mini'",JSON.stringify({geral:3,programacao:3,raciocinio:3,precisao:3,leitura_longa:3}));const r=escolher(a,'classe:equilibrado',{analise:analisarPedido({texto:'Analise este código, encontre o problema e proponha uma correção considerando concorrência, performance e segurança.'})});assert.equal(r.modelo.id,'openai/gpt-5.4-mini');assert.equal(r.fallback,null);}finally{a.db.close();}});
test('dados sigilosos nunca usam modelos novos sem autorização e não têm reserva livre do fornecedor',()=>{const a=app();try{ampliarPoolsRecomendados(a);const id='google/gemini-3.5-flash-lite';exec(a.db,"update modelos set homologado=1,homologacao=? where id=?",JSON.stringify({fornecedor:'Google',endpoint:'google-vertex',retencaoZero:true,semTreino:true}),id);const r=escolher(a,'classe:rapido',{sigilosa:true});assert.equal(r.modelo.id,id);assert.equal(r.reserva,null);assert.ok(r.candidatos.filter(c=>c.id!==id).every(c=>c.motivos.includes('nao_homologado')));}finally{a.db.close();}});
test('modelo técnico explicitamente fixado no Quick Win continua fixo',()=>{const a=app();try{ampliarPoolsRecomendados(a);const cfg=lerConfig(a.db),id=cfg.padroes.rapido;const r=escolher(a,'classe:rapido',{qw:{modelo:id,pode_trocar:false},modeloManual:acharModelo(a.db,cfg,id),origem:'quick_win'});assert.equal(r.modelo.id,id);assert.equal(r.reserva,null);}finally{a.db.close();}});
test('modelo retirado do catálogo não participa; falha de consulta preserva catálogo conhecido',async()=>{const a=app();try{ampliarPoolsRecomendados(a);const id=lerConfig(a.db).padroes.rapido;exec(a.db,'update modelos set no_catalogo=0 where id=?',id);const r=escolher(a);assert.notEqual(r.modelo.id,id);assert.ok(r.candidatos.find(c=>c.id===id).motivos.includes('fora_do_catalogo'));assert.notEqual(resolverClasse(a.db,lerConfig(a.db),'classe:rapido'),id);a.ia.listarModelos=async()=>{throw Error('rede indisponível');};await assert.rejects(atualizarCatalogo(a));assert.equal(todos(a.db,'select * from modelos where no_catalogo=1').length,8);}finally{a.db.close();}});
test('falhas e latência só pesam com amostra suficiente, são auditadas e não escapam do nível',()=>{const a=app();try{ampliarPoolsRecomendados(a);const id=lerConfig(a.db).padroes.rapido;for(let i=0;i<4;i++)observacao(a,id,'falha_na_execucao');assert.equal(desempenhoRecente(a.db,agora).get(id).penalidade,0);observacao(a,id,'falha_na_execucao');const r=escolher(a,'classe:rapido');assert.notEqual(r.modelo.id,id);assert.equal(r.modelo.perfil,'rapido');assert.equal(r.candidatos.find(c=>c.id===id).desempenho.falhas,5);const outro=r.modelo.id;for(let i=0;i<5;i++)observacao(a,outro,'respondido',5000);assert.ok(desempenhoRecente(a.db,agora).get(outro).penalidade>0);}finally{a.db.close();}});
test('dados antigos, bloqueios de governança e resultados ainda incompletos não contaminam desempenho',()=>{const a=app();try{const id=lerConfig(a.db).padroes.rapido;for(const resultado of ['bloqueado','enviado'])for(let i=0;i<6;i++)observacao(a,id,resultado);observacao(a,id,'falha_na_execucao',1000,'2026-09-01T00:00:00Z');assert.equal(desempenhoRecente(a.db,agora).size,0);observacao(a,id,'respondido_pela_reserva',3000,agora.toISOString(),'openai/gpt-5-mini');const d=desempenhoRecente(a.db,agora);assert.equal(d.get(id).falhas,1);assert.equal(d.get('openai/gpt-5-mini').falhas,0);}finally{a.db.close();}});

test('curadoria seleciona modelos diferentes para tarefas distintas no mesmo nível, com custo e governança mantidos',()=>{const a=app();try{ampliarPoolsRecomendados(a);const codigo=escolher(a,'classe:rapido',{analise:analisarPedido({texto:'Escreva uma função Python simples para converter uma lista de valores.'})});const triagem=escolher(a,'classe:rapido',{analise:analisarPedido({texto:'Classifique estes itens por categoria: lápis, papel e caneta.'})});assert.equal(codigo.modelo.id,'openai/gpt-5-mini');assert.notEqual(codigo.modelo.id,triagem.modelo.id);assert.equal(codigo.modelo.perfil,'rapido');assert.equal(triagem.modelo.perfil,'rapido');assert.ok(codigo.candidatos.find(c=>c.id===codigo.modelo.id).afinidade>0);}finally{a.db.close();}});
